# Generated by Django 4.1.7 on 2023-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='href',
            field=models.SlugField(default='', unique=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='href',
            field=models.SlugField(default='', unique=True, verbose_name='href'),
        ),
    ]
