# Generated by Django 4.1.7 on 2023-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0009_product_tags_alter_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='href',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='product',
            name='href',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='href',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='href'),
        ),
    ]
