# Generated by Django 4.1.7 on 2023-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0015_remove_category_href_remove_product_href_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='app_products.category', verbose_name='subcategories'),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='isLimited',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='review',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='specification',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
