# Generated by Django 4.1.7 on 2023-04-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
