# Generated by Django 4.1.7 on 2023-04-20 17:33

import app_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_rename_number_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.CharField(max_length=16, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=3, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(max_length=2, validators=[app_orders.models.validate_card_year], verbose_name='year'),
        ),
    ]
