# Generated by Django 4.1.7 on 2023-04-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('fullName', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('deliveryType', models.CharField(max_length=20, verbose_name='delivery type')),
                ('paymentType', models.CharField(max_length=20, verbose_name='payment type')),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total cost')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
