# Generated by Django 4.1.7 on 2023-04-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0005_userprofile_email'),
        ('app_orders', '0003_orderproduct_count_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_profiles.userprofile', verbose_name='user'),
        ),
    ]
