# Generated by Django 4.1.7 on 2023-04-08 09:31

import app_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_products.models.category_image_directory_path, verbose_name='image'),
        ),
    ]
