# Generated by Django 4.1.7 on 2023-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_rename_quantity_product_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tag name')),
            ],
        ),
    ]
