# Generated by Django 4.1.7 on 2023-04-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_producttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'product tag', 'verbose_name_plural': 'product tags'},
        ),
    ]
