# Generated by Django 4.1.7 on 2023-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_alter_producttag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='app_products.producttag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='reviews'),
        ),
    ]
