# Generated by Django 4.1.7 on 2023-04-14 14:41

import app_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0011_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_products.models.sale_item_images_directory_path, verbose_name='image')),
                ('saleItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_products.saleitem', verbose_name='product')),
            ],
            options={
                'verbose_name': 'sale item image',
                'verbose_name_plural': 'sale item images',
            },
        ),
    ]
