# Generated by Django 4.1.7 on 2023-04-16 11:01

import app_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0013_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('rate', models.DecimalField(decimal_places=0, max_digits=1, validators=[app_products.models.validate_rate], verbose_name='rate')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
