# Generated by Django 4.1.7 on 2023-04-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0014_remove_product_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='href',
        ),
        migrations.RemoveField(
            model_name='product',
            name='href',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='href',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='href',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='app_products.product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
