# Generated by Django 4.1.7 on 2023-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0016_category_available_category_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isLimited',
            field=models.BooleanField(default=False, verbose_name='is limited'),
        ),
    ]
