# Generated by Django 4.1.7 on 2023-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0017_alter_product_islimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(blank=True, verbose_name='full description'),
        ),
    ]
